language: python
python:
- '3.6'
- '2.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: mathewmarcus
  password:
    secure: ND7qCTADIakLAtaD/aP6Vr6JhHaIxLpsneLu/buh4Kohg2PT5veI8Bj1V2dMnvo2gK+YAgAMLPBZMxPuIeQbQFXdf2sh69cChQsGfior7N/f4U8mIsR5mtDcAQmT1Qa3c2mEh9pSMpevuj6lJwfEAHbiK3lvIBR0pp6zUIZICewkNZAFZclwsPs+ADAB7A8SI0xkaXQIsdKFY3liHqXIGztF+SgpLyumvGjkcybHgPl/HkxqHPfuPmDy1QPpZMdfzENwWbl810y4Gqfh2ZnRhC09elDdsgITtnE5ABSs8/xaEpIzD8rCeQ4b+ooywZggKZ9bB2Ja0LCWyGt6BixpswJv1hwtRQcv2PePZNVSAFc2IVSyeMI5wfNP3uIdvPSXgaRE9huPxXWc1CwxB/Q8RF2jxbB3yBS3eDGBswGI5QX6ypTv9xrjo67dGO8E0g5adbRYA91+RRGLSh6F1RUCtZU0X2JdTIofegLHMv6jQQgsFqqJlk7I8aUF/mHlI3ffCAKytFNwTHp6CKU6BJc3uyChEN3DRPPvkUDOSglNkq8vT9uO9fqC2EZJOANr2qyMWsuJ3ffFcyCUs6SUeP8mCABF65jHF9e8++e87wfalIgBayuB+XZXUWRjS4/EBq0j940+AM9ryGxqJAQGmTOq60bSzxv0ukRoGNoqzKnVX6I=
  on:
    branch: release
